### ISSUE TITLE
Error on retrieving phone number.

### ISSUE THREAD

**Issue by msounkere** [Gandi/whmcs_Gandi-module#1]
Hello Team 
We get the following error on each domain activation. 
It's related to the phone number. Tn this case the user has wrote +225 07018649
{"status":"error","errors":[{"location":"body","name":"owner.phone","description":"+225.7018649 is an invalid telephone number."}]}
Last Attempt: 1 day ago

**Comment by grigouze** [comment]
@msounkere The phone number seems invalid for the phone checker.
Because it drop the first "0" there is not enough digits for a "CI" phone number.

**Comment by msounkere** [comment]
@grigouze Yes this is what we got when the user fills the registration form. After some research in the database, it seems that WHMCS has fixed this error and now we have to script our database to correct all wrong numbers registered.

**Comment by mxdjo** [comment]
Hello @msounkere please how did you fix the issue?
We are facing the same issue.

**Comment by msounkere** [comment]
Directly in database with a script to fix wrong number.
