### ISSUE TITLE
Transferred domains are stuck in "Pending transfer" status in WHMCS

### ISSUE THREAD

**Issue by julienmru** [Gandi/whmcs_Gandi-module#14]
After a domain name is successfully transferred to Gandi, its status is stuck as "Pending transfer", even after several days, forcing a WHMCS agent to manually change the status to "Active"

Upon discussing with the support, it seems the TransferSync code is missing from the module.

**Comment by grigouze** [comment]
The Merge request is created but not already pushed.

I will ping you when it's ready

**Comment by grigouze** [comment]
I created the MR #15

**Comment by julienmru** [comment]
Thanks, it's working as expected :)
