### ISSUE TITLE
The transfer endpoint seems to be outdated

### ISSUE THREAD

**Issue by Fyroeo** [Gandi/whmcs_Gandi-module#6]
Hello 👋 

It seems like the transfer endpoint is actually outdated, making the module to fail any incoming transfer.
I made some modifications on my side to make it "works", but I don't consider theses modifications eligible for a pull-request. (I'm not that experimented in PHP).

In `modules/registrars/gandiv5/lib/ApiClient.php`:

- Line 60: Changed `$url = "{$this->endPoint}/domain/domains";` to `$url = "{$this->endPoint}/domain/transferin";`
- Line 73: Changed
`        $params = [
            "fqdn" => $domain,
            "duration" => $period,
            "owner" => $owner,
            "nameservers" => $nameservers
        ];` to `         $params = [
            "fqdn" => $domain,
            "duration" => $period,
            "owner" => $owner,
            "nameservers" => $nameservers,
            "authinfo" => $authCode
        ];`

Now, I was unable to resolve these issues in a proper way:

- The transfer function is not using the $organization parameter for billing. I was able to resolve this by manually adding "?sharing_id=xxx" to the transferin endpoint.
- The state of the owner (line 69) is always misconfigured for the API. The API is waiting for something like "FR-ARA", but WHMCS will return "FR-LOIRE" for someone living in the Loire department. As a result, the request fail. I don't know how this would be properly resolved.

This issue is more an indication to where the problems are actually, but I'm sure that it will help you.

Kind Regards,
Thomas

**Comment by grigouze** [comment]
@Fyroeo You're right :)

I created a new PR #7 

Thanks for the report.

**Comment by grigouze** [comment]
@Fyroeo It's merged.

Thanks again.
