### ISSUE TITLE
Domains registered as individuals even for companies

### ISSUE THREAD

**Issue by julienmru** [Gandi/whmcs_Gandi-module#9]
Domain registered to a company in WHMCS is registered as individual on Gandi.net.

**Comment by julienmru** [comment]
The changed proposed does not handle "association" or "publicbody" for associations and public bodies.

**Comment by grigouze** [comment]
Thanks for reporting the issue.

I think it's ok for others types.

When I look to your #10 , I think I can close the #8 because it will add a conflict.

**Comment by julienmru** [comment]
> When I look to your #10 , I think I can close the #8 because it will add a conflict.

Yes, or you merge #8 first.
